# syntax=docker/dockerfile:1
FROM       node:alpine
MAINTAINER Stevie "https://github.com/yzm629"

# buildkit: https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md

RUN --mount=type=cache,target=/root/.npm,id=npm_cache \
    npm i -g verdaccio

EXPOSE 9000

CMD ["verdaccio", "--listen", "0.0.0.0:9000"]
